#! /usr/bin/env python3

import argparse

import wikicurses.ui as ui
from wikicurses.wiki import wiki

parser = argparse.ArgumentParser(description =
                                    "A simple curses interface for accessing Wikipedia.")

parser.add_argument('search',
                    nargs = '?',
                    default = '',
                    help = "Page to search for on Wikipedia")

group = parser.add_mutually_exclusive_group()
group.add_argument('-d', '--today',
                    action = 'store_const',
                    const = 'onthisday',
                    help='Display URLs for the "On this day" pages')
group.add_argument('-f', '--featured',
                    action = 'store_const',
                    const = 'featured',
                    help = 'Display the featured articles URLs')
group.add_argument('-p', '--picture',
                    action = 'store_const',
                    const = 'potd',
                    help='Display URLs for the "Picture of the day" pages')

args = parser.parse_args()

if args.search :
    ui.setContent(wiki.search(args.search))
else:
    feed = args.featured or args.picture or args.today
    feed = feed or 'featured'
    ui.setContent(wiki.get_featured_feed(feed))
ui.loop.run()
