.TH wikicurses.conf 5 2015-02-22
.SH NAME
wikicurses \- curses interface for MediaWiki
.SH SYNOPSIS
/etc/wikicurses.conf

~/.config/wikicurses/config
.SH DESCRIPTION
The configuration file for wikicurses is divided into sections with the "general" section containing general settings.  All other sections specify individual wikis.
.SH EXAMPLE
.nf
[general]
default = Wikipedia
mouse = False
hide_references = False

[keymap]
q = quit
c = contents
o = open
h = back
l = forward
left = back
right = forward

[Wikipedia]
url = http://en.wikipedia.org/w/api.php
username = johndoe
password = 1234

[ArchWiki]
url = https://wiki.archlinux.org/api.php
.SH OPTIONS
.SS general
.PP
default
.RS 4
The name of the wiki to use by default
.RE
.PP
mouse
.RS 4
Support mouse input. With this enabled, you will have to hold down shift to select text.
.RE
.PP
hide_references
.RS 4
Hide the References section at the bottom of the page and strip citations from the text.
.RE
.SS keymap
This section configures the keyboard bindings of wikicurses, in the format "key=command". Command can be any ex command supported by wikicurses.
.SS Other Sections
Other sections are treated as wiki entries. The url is the url for api.php on the wiki. The username and password are required for editing.
.PP
url
.RS 4
The url to api.php on the MediaWiki site
.RE
