.TH wikicurses 1 2015-04-10
.SH NAME
wikicurses \- curses interface for MediaWiki
.SH SYNOPSIS
wikicurses [\-h] [\-\-wiki WIKI] [\-d | \-f | \-p] [search]
.SH CONTROLS
.SS General
.PP
j or down
.RS 4
Scroll down
.RE
.PP
k or up
.RS 4
Scroll up
.RE
.PP
^b or pagedown
.RS 4
Scroll down one page
.RE
.PP
^f or pageup
.RS 4
Scroll up one page
.RE
.PP
g or home
.RS 4
Scroll to top
.RE
.PP
G or end
.RS 4
Scroll to bottom
.RE
.SS Pager
.PP
c
.RS 4
Open table of contents
.RE
.PP
o
.RS 4
Open search box
.RE
.PP
q or :q[uit]
.RS 4
Exit
.RE
.PP
:bmark
.RS 4
Bookmark page
.RE
.PP
:bmarks
.RS 4
Open bookmarks
.RE
.PP
:links
.RS 4
Open list of internal links in page
.RE
.PP
:iwlinks
.RS 4
Open list of interwiki links in page
.RE
.PP
:extlinks
.RS 4
Open list of external links in page to open in browser
.RE
.PP
:langs
.RS 4
Open list of languages the article is available in
.RE
.PP
:wikis
.RS 4
Open list of configured wikis, see \fBwikicurses.conf\fR(5)
.RE
.PP
:feeds
.RS 4
Open a list of featured feeds on the current wiki
.RE
.PP
:clearcache
.RS 4
Clears the cache; exiting the program has an equivalent effect
.RE
.PP
:edit
.RS 4
Edit wiki page (opens in $EDITOR)
.RE
.PP
:help
.RS 4
Display man page
.RE
.PP
:back, h, or left
.RS 4
Go backward in history
.RE
.PP
:forward, l, or right
.RS 4
Go forward in history
.RE
.PP
:random
.RS 4
Go to a random page
.RE
.PP
/
.RS 4
Search page and highlight matching text. Supports regular expressions.
.RE
.SS Bookmarks Menu
.PP
x or delete
.RS 4
Delete selected bookmark
.RE
.PP
u
.RS 4
Undo deletion
.RE
.SS Search
.PP
tab
.RS 4
Tab completion for page title
.RE
.SH OPTIONS
.PP
\fB\-h,\fR \-\-help
.RS 4
Display help message
.RE
.PP
\fB\-w,\fR \-\-wiki <wiki>
.RS 4
Url or name of wiki to use
.RE
.PP
\fB\-f,\fR \-\-feed <name>
.RS 4
view featured feed
.RE
.PP
\-\-dumpcolors
.RS 4
write current color settings to config file
.RE
.SH COLOR SETTINGS
To use colors other than the defaults, you need a file called ~/.config/wikicurses/colors.  To create this file with the current color settings, run wikicurses --dumpcolors.  This is a configuration file containing various things that can be colored.  Each has allows setting display settings (bold, underline, or standout), foreground color, and background color.  Multiple settings can be set by separating with spaces.  The color options are the same as in urwid (see http://urwid.org/manual/displayattributes.html).
.SH ENVIRONMENT VARIABLES
.PP
HOME, XDG_CONFIG_HOME
.RS 4
Determines where to look for and store configuration files.
.RE
.PP
EDITOR
.RS 4
The name of the command to use as a text editor, defaulting to vim.
.RE
.PP
BROWSER
.RS 4
The name of the command to use as a web browser, defaulting to lynx.
.SH EXAMPLES
.PP
wikicurses Wiki
.RS 4
Look up "Wiki" on the default wiki
.RE
.PP
wikicurses -w ArchWiki Dwm
.RS 4
Look up "Dwm" on the Archlinux Wiki, where "ArchWiki" is configured in \fbwikicurses.conf\fr(5)
.RE
.PP
wikicurses -w http://en.wiktionary.org/w/api.php penguin
.RS 4
Look up "penguin" on Wiktionary
.RE
.PP
wikicurses -f potd
.RS 4
Open "potd" (Picture of the Day) feed
.RE
.SH SEE ALSO
\fBwikicurses.conf\fR(5)
.SH BUGS
https://github.com/ids1024/wikicurses/issues
