#! /usr/bin/env python3

import sys
import argparse
import wikicurses.ui as ui
from wikicurses import settings

parser = argparse.ArgumentParser(
        description="A simple curses interface for accessing Wikipedia.")

parser.add_argument('search',
                    nargs = '?',
                    default = 'Main page',
                    help = "page to search for")
parser.add_argument('-w', '--wiki', help='wiki api url')
#For shell completion functions
parser.add_argument('--complete',
                    action = 'store',
                    help = argparse.SUPPRESS)

parser.add_argument('-f', '--feed', help = 'view featured feed')

args = parser.parse_args()
settings.openWiki(args.wiki)

if args.complete:
    if args.complete == 'search':
        sugestions = settings.wiki.search_sugestions(args.search)
    elif args.complete == 'feed':
        sugestions = settings.wiki.list_featured_feeds()
    elif args.complete == 'wiki':
        sugestions = settings.wikis().keys()
    print(*sugestions, sep='\n')
    sys.exit()

if args.feed:
    ui.setContent(settings.wiki.get_featured_feed(args.feed))
else:
    ui.setContent(settings.wiki.search(args.search))

try:
    ui.loop.run()
except KeyboardInterrupt:
    pass

if settings.wiki.csrftoken:
    settings.wiki.logout()
